PACKAGE_NAME="8190p"
PACKAGE_VERSION="1.1"

MAKE[0]="make KVER=${kernelver}"
CLEAN="make KVER=${kernelver} clean"

BUILT_MODULE_NAME[0]="8190p"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless"

POST_INSTALL="dkms-post-install.sh"

AUTOINSTALL="yes"